# Makefile for GNU make
HDRLOC_CORE += config
HDRLOC_CORE += include
HDRLOC_CORE += include/stdc
HDRLOC_CORE += include/stdc/sys
include $(SYS_DRV_LOC)/Makefile
include $(SYS_FS_LOC)/Makefile
include $(SYS_INIT_LOC)/Makefile
include $(SYS_KRN_LOC)/Makefile
include $(SYS_LIB_LOC)/Makefile
include $(SYS_MM_LOC)/Makefile
include $(SYS_NET_LOC)/Makefile
include $(SYS_PORT_LOC)/Makefile
