# Makefile for GNU make
include $(DRV_LOC)/loop/Makefile
include $(DRV_LOC)/gpio/Makefile
include $(DRV_LOC)/afio/Makefile
include $(DRV_LOC)/crcm/Makefile
include $(DRV_LOC)/ethmac/Makefile
include $(DRV_LOC)/pll/Makefile
include $(DRV_LOC)/sdspi/Makefile
include $(DRV_LOC)/spi/Makefile
include $(DRV_LOC)/tty/Makefile
include $(DRV_LOC)/uart/Makefile
include $(DRV_LOC)/wdg/Makefile
include $(DRV_LOC)/usb/Makefile
include $(DRV_LOC)/irq/Makefile
include $(DRV_LOC)/i2c/Makefile
