# Makefile for GNU make
CSRC_CORE   += drivers/drvctrl.c
CSRC_CORE   += ../../$(GEN_DRIVERS_DIR)/driver_registration.c
CSRC_CORE   += drivers/class/storage/mbr.c
CSRC_CORE   += drivers/class/storage/sd.c
HDRLOC_CORE += drivers

-include $(GEN_DRIVERS_DIR)/Makefile.in
