# Makefile for GNU make
ifeq ($(ENABLE_TTY), __YES__)
   CSRC_NOARCH   += drivers/tty/tty.c
   CSRC_NOARCH   += drivers/tty/tty_bfr.c
   CSRC_NOARCH   += drivers/tty/tty_cmd.c
   CSRC_NOARCH   += drivers/tty/tty_editln.c
   CXXSRC_NOARCH += 
   HDRLOC_NOARCH += drivers/tty
endif
