# Makefile for GNU make

CSRC_LIB   += zlib/adler32.c
CSRC_LIB   += zlib/compress.c
CSRC_LIB   += zlib/crc32.c
CSRC_LIB   += zlib/deflate.c
CSRC_LIB   += zlib/gzclose.c
CSRC_LIB   += zlib/gzlib.c
CSRC_LIB   += zlib/gzread.c
CSRC_LIB   += zlib/gzwrite.c
CSRC_LIB   += zlib/infback.c
CSRC_LIB   += zlib/inffast.c
CSRC_LIB   += zlib/inflate.c
CSRC_LIB   += zlib/inftrees.c
CSRC_LIB   += zlib/trees.c
CSRC_LIB   += zlib/uncompr.c
CSRC_LIB   += zlib/zutil.c
CXXSRC_LIB +=
HDRLOC_LIB += zlib
