# Makefile for GNU make
CSRC_CORE += fs/procfs/procfs.c
CSRC_CORE += fs/lfs/lfs.c
CSRC_CORE += fs/fatfs/fatfs.c
CSRC_CORE += fs/fatfs/libfat/libfat_user.c
CSRC_CORE += fs/fatfs/libfat/libfat.c
CSRC_CORE += fs/fatfs/libfat/libfat_unicode.c
CSRC_CORE += fs/devfs/devfs.c
CSRC_CORE += fs/fs_registration.c
