# Makefile for GNU make
CSRC_CORE   += lib/btree.c
CSRC_CORE   += lib/conv.c
CSRC_CORE   += lib/llist.c
CSRC_CORE   += lib/vsnprintf.c
CSRC_CORE   += lib/vfprintf.c
CSRC_CORE   += lib/vsscanf.c
HDRLOC_CORE += lib
