# Makefile for GNU make
CSRC_CORE   += lib/btree.c
CSRC_CORE   += lib/conv.c
CSRC_CORE   += lib/llist.c
CSRC_CORE   += lib/vsnprintf.c
CSRC_CORE   += lib/vfprintf.c
CSRC_CORE   += lib/vsscanf.c
CSRC_CORE   += lib/stropt.c
CSRC_CORE   += lib/strchrrep.c
CSRC_CORE   += lib/strlcat.c
CSRC_CORE   += lib/strlcpy.c
CSRC_CORE   += lib/strcasecmp.c
CSRC_CORE   += lib/rand.c
HDRLOC_CORE += lib
