# Makefile for GNU make
__CPUCONFIG_CPUNAME__=STM32F107RCxx
CPUCONFIG_AFLAGS=-mcpu=cortex-m3 -mthumb -mthumb-interwork -DGCC_ARMCM3
CPUCONFIG_CFLAGS=-mcpu=cortex-m3 -mthumb -mthumb-interwork -DGCC_ARMCM3
CPUCONFIG_CXXFLAGS=-mcpu=cortex-m3 -mthumb -mthumb-interwork -DGCC_ARMCM3
CPUCONFIG_LDFLAGS=-mcpu=cortex-m3 -mthumb -mthumb-interwork
CPUCONFIG_LD=./src/system/portable/stm32f1/ld/$(__CPUCONFIG_CPUNAME__).ld
