# Makefile for GNU make
CPUCONFIG_CPUNAME=STM32F107RCxx
CPUCONFIG_AFLAGS   = -mcpu=cortex-m3 -mthumb -mthumb-interwork -DGCC_ARMCM3
CPUCONFIG_CFLAGS   = -mcpu=cortex-m3 -mthumb -mthumb-interwork -DGCC_ARMCM3
CPUCONFIG_CXXFLAGS = -mcpu=cortex-m3 -mthumb -mthumb-interwork -DGCC_ARMCM3
CPUCONFIG_LDFLAGS  = -mcpu=cortex-m3 -mthumb -mthumb-interwork
CPUCONFIG_LD       = src/system/portable/stm32f1/ld/$(CPUCONFIG_CPUNAME).ld
