# Makefile for GNU make
CSRC_CORE += core/dnx.c
CSRC_CORE += core/sysmoni.c
CSRC_CORE += core/progman.c
CSRC_CORE += core/pipe.c
CSRC_CORE += core/list.c
CSRC_CORE += core/main.c
CSRC_CORE += core/memman.c
CSRC_CORE += core/scanx.c
CSRC_CORE += core/printx.c
CSRC_CORE += core/vfs.c
CSRC_CORE += core/modctrl.c
CSRC_CORE += core/fsctrl.c
CSRC_CORE += core/conv.c