# Makefile for GNU make

# NOTE: All flags defined as: __FLAG_NAME__ (with doubled underscore as suffix
#       and prefix) are exported to the single configuration file
#       (by using Configtool) when entire project configuration is exported.
#       All other flag definitions and statements are ignored.

# project configuration
__PROJECT_NAME__=dnx
__PROJECT_CPU_ARCH__=stm32f1
__PROJECT_TOOLCHAIN__=arm-none-eabi-

# file system enable flags
__ENABLE_LFS__=_YES_
__ENABLE_DEVFS__=_YES_
__ENABLE_PROCFS__=_YES_
__ENABLE_FATFS__=_YES_

# modules enable flags
__ENABLE_LOOP__=_YES_
__ENABLE_GPIO__=_YES_
__ENABLE_AFIO__=_YES_
__ENABLE_CRC__=_YES_
__ENABLE_ETH__=_YES_
__ENABLE_PLL__=_YES_
__ENABLE_SDSPI__=_YES_
__ENABLE_SPI__=_YES_
__ENABLE_TTY__=_YES_
__ENABLE_UART__=_YES_
__ENABLE_WDG__=_YES_
__ENABLE_USB__=_NO_
__ENABLE_I2C__=_YES_
__ENABLE_IRQ__=_YES_

# network
__ENABLE_NETWORK__=_YES_
