# Makefile for GNU make

# project configuration
PROJECT_NAME="dnx"
PROJECT_CPU_ARCH=stm32f1
PROJECT_TOOLCHAIN=arm-none-eabi-

# file system enable flags
ENABLE_LFS=__YES__
ENABLE_DEVFS=__YES__
ENABLE_PROCFS=__YES__
ENABLE_FATFS=__YES__

# modules enable flags
ENABLE_CRC=__YES__
ENABLE_ETHMAC=__YES__
ENABLE_PLL=__YES__
ENABLE_SDSPI=__YES__
ENABLE_SPI=__NO__
ENABLE_TTY=__YES__
ENABLE_UART=__YES__
ENABLE_WDG=__YES__

# network
ENABLE_NETWORK=__YES__
