# Makefile for GNU make
CSRC_CORE += fs/ext4fs/ext4fs.c
CSRC_CORE += fs/ext4fs/lwext4/src/ext4_balloc.c
CSRC_CORE += fs/ext4fs/lwext4/src/ext4_bcache.c
CSRC_CORE += fs/ext4fs/lwext4/src/ext4_bitmap.c
CSRC_CORE += fs/ext4fs/lwext4/src/ext4_blockdev.c
CSRC_CORE += fs/ext4fs/lwext4/src/ext4_block_group.c
CSRC_CORE += fs/ext4fs/lwext4/src/ext4.c
CSRC_CORE += fs/ext4fs/lwext4/src/ext4_crc32.c
CSRC_CORE += fs/ext4fs/lwext4/src/ext4_debug.c
CSRC_CORE += fs/ext4fs/lwext4/src/ext4_dir.c
CSRC_CORE += fs/ext4fs/lwext4/src/ext4_dir_idx.c
CSRC_CORE += fs/ext4fs/lwext4/src/ext4_extent.c
CSRC_CORE += fs/ext4fs/lwext4/src/ext4_fs.c
CSRC_CORE += fs/ext4fs/lwext4/src/ext4_hash.c
CSRC_CORE += fs/ext4fs/lwext4/src/ext4_ialloc.c
CSRC_CORE += fs/ext4fs/lwext4/src/ext4_inode.c
CSRC_CORE += fs/ext4fs/lwext4/src/ext4_journal.c
CSRC_CORE += fs/ext4fs/lwext4/src/ext4_mkfs.c
CSRC_CORE += fs/ext4fs/lwext4/src/ext4_super.c
CSRC_CORE += fs/ext4fs/lwext4/src/ext4_trans.c
CSRC_CORE += fs/ext4fs/lwext4/src/ext4_xattr.c

HDRLOC_CORE += fs/ext4fs
HDRLOC_CORE += fs/ext4fs/lwext4/include
